// AUTO-GENERATED by scripts/mirror-images.mjs
// Do not edit manually. Update image-sources.json instead.

export type ManifestItem = { file: string; label?: string };

export const renderingFiles: ManifestItem[] = [
  { file: "enggrass1.png" },
  { file: "enggrass2.png" },
  { file: "Engrass_Lofts_Exterior_Corner_View.jpg" },
  { file: "Engrass_Lofts_Exterior_Lawrence_Street.jpg" },
  { file: "Engrass_Lofts_Unit1_Front_Section.jpg" },
  { file: "Engrass_Lofts_Unit1_Kitchen_Living.jpg" },
  { file: "Engrass_Lofts_Unit1_Loft_Detail.jpg" },
  { file: "Engrass_Lofts_Unit1_Section_View.jpg" },
  { file: "Engrass_Lofts_Unit2_Axon_View.jpg" },
  { file: "Engrass_Lofts_Unit2_Interior_View.jpg" },
  { file: "Engrass_Lofts_Unit2_Loft_Truss.jpg" },
  { file: "Engrass_Lofts_Unit2_Section_View.jpg" },
  { file: "pasteboard-01.jpg" },
  { file: "pasteboard-02.jpg" },
  { file: "pasteboard-03.jpg" },
  { file: "pasteboard-04.jpg" },
  { file: "pasteboard-05.jpg" },
  { file: "pasteboard-06.jpg" },
  { file: "pasteboard-unit-2.jpg" },
  { file: "rendering-01.jpg" },
  { file: "rendering-02.jpg" },
  { file: "rendering-03.jpg" },
  { file: "rendering-04.jpg" },
  { file: "rendering-05.jpg" },
  { file: "rendering-06.jpg" },
  { file: "rendering-unit-2.jpg", label: "Unit 2" },
];

export const historyFiles: ManifestItem[] = [
  { file: "Gemini_Generated_Image_1zgnpm1zgnpm1zgn.png" },
  { file: "history-01.jpg" },
  { file: "history-original-building.png", label: "Original Enggrass Building" },
];
